name: Sync ArgoCD Project

env:
  ARGOCD_SERVER: gitops-shared.apps.silver.devops.gov.bc.ca
  SERVICE:
  ENV:
jobs:
  sync-argocd-project:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.7.4/argocd-linux-amd64
      - name: Set Permissions
        run: |
          chmod 755 /usr/local/bin/argocd
      - name: Sync ArgoCD Project
        run: |
          argocd app sync \
            --grpc-web \
            --server ${{ARGOCD_SERVER}} \
            --auth-token ${{secrets.ARGOCD_TOKEN}} \
            mds-${{SERVICE}}-${{ENV}}
      - name: Wait for rollout
        run: |
          argocd app wait \
            --grpc-web
            --server ${{ARGOCD_SERVER}} \
            --auth-token ${{secrets.ARGOCD_TOKEN}} \
            mds-${{SERVICE}}-${{ENV}}
      