on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string
      test-report-artifact:
        required: false
        type: string
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.test-report-artifact }}
      - run: ls -R


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        with:
          projectBaseDir: ${{ inputs.project-dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
